
# tap repositories and their packages

tap caskroom/cask
brew brew-cask
cask anki
cask appcleaner
cask atom
cask betterzipql
cask box-sync
cask brackets
cask ccleaner
cask clipy
cask coteditor
cask cyberduck
cask doxygen
cask exa
cask gimp
cask google-chrome
cask hipchat
cask iterm2
cask karabiner
cask keepassx
cask keka
cask keycastr
cask launchy
cask libreoffice
cask licecap
cask macwinzipper
cask manuscripts
cask mysqlworkbench
cask netbeans-php
cask octohub
cask otto
cask owasp-zap
cask p4merge
cask packer
cask qlcolorcode
cask qlmarkdown
cask qlprettypatch
cask qlstephen
cask quicklook-csv
cask quicklook-json
cask seil
cask sequel-pro
cask sourcetree
cask sqlitebrowser
cask terraform
cask vagrant
cask vault
cask virtualbox
cask vlc
cask xmind

tap caskroom/fonts
cask font-myrica
cask font-myricam
cask font-ricty-diminished
cask font-source-han-code-jp
cask font-source-han-sans

tap homebrew/completions
brew brew-cask-completion
brew packer-completion
brew vagrant-completion
brew wpcli-completion

tap homebrew/dupes

tap homebrew/php
brew behat
brew codeception
brew pdepend
brew php56-imagick
brew php56-intl
brew php56-opcache
brew php56-phalcon
brew php56-twig
brew php56-xdebug
brew php56-yaml
brew php56
brew phpcpd
brew phploc
brew phpmd
brew phpmetrics
brew phpunit

tap rcmdnk/file
brew brew-file

tap tldr-pages/tldr

# Other Homebrew packages
brew ack
brew android-sdk
brew ansible
brew autoconf
brew awscli
brew bash-completion
brew bash-git-prompt
brew bison
brew boost
brew caddy
brew cmake
brew composer
brew ctags
brew curl
brew editorconfig
brew freetype
brew gettext
brew gflags
brew ghostscript
brew git
brew git-flow
brew glog
brew gmp
brew graphviz
brew highlight
brew httpie
brew hubflow
brew icu4c
brew imagemagick
brew jbig2dec
brew jmeter
brew jpeg
brew jq
brew libgit2
brew libpng
brew libtiff
brew libtool
brew libxml2
brew libyaml
brew libzip
brew little-cms2
brew lua
brew lz4
brew mecab
brew mecab-ipadic
brew mycli
brew nkf
brew nodebrew
brew oniguruma
brew openssl
brew p7zip
brew pandoc
brew pcre
brew php-code-sniffer
brew php-cs-fixer
brew php56-mecab
brew phpdocumentor
brew phpunit-skeleton-generator
brew pkg-config
brew pre-commit
brew q
brew rbenv
brew readline
brew rename
brew rocksdb
brew ruby-build
brew shellcheck
brew snappy
brew sqlite
brew ssh-copy-id
brew subversion
brew the_silver_searcher
brew thrift
brew tig
brew tldr
brew trash
brew tree
brew unar
brew unixodbc
brew unrar
brew vim
brew wget
brew xz
brew zlib

# gem packages
gem completion

# App Store applications
appstore Dash
appstore Go2Shell
appstore Growl
appstore Keynote
appstore Simplenote
appstore Tweetbot
appstore Xcode

# Other commands
but not corresponding casks were found.
