
# tap repositories and their packages

## caskroom/cask
tap caskroom/cask
brew brew-cask
cask appcleaner
cask asepsis
cask atom
cask betterzipql
cask box-sync
cask brackets
cask ccleaner
cask clamxav
cask coteditor
cask cyberduck
cask dash
cask doxygen
cask flashlight
cask gimp
cask google-chrome
cask hipchat
cask iterm2
cask karabiner
cask keepassx
cask keka
cask keycastr
cask launchy
cask libreoffice
cask licecap
cask macwinzipper
cask mysqlworkbench
cask netbeans-php
cask node
cask owasp-zap
cask p4merge
cask packer
cask qlcolorcode
cask qlmarkdown
cask qlprettypatch
cask qlstephen
cask quicklook-csv
cask quicklook-json
cask seil
cask sequel-pro
cask sourcetree
cask sqlitebrowser
cask vagrant
cask virtualbox
cask vlc
cask xmind
cask xquartz
cask xtrafinder

## homebrew/completions
tap homebrew/completions
brew gem-completion
brew packer-completion
brew vagrant-completion
brew wpcli-completion

## homebrew/dupes
tap homebrew/dupes
brew zlib

## homebrew/php
tap homebrew/php
brew composer
brew php56-imagick
brew php56-mecab
brew php56-mongo
brew php56-opcache
brew php56-phalcon
brew php56-twig
brew php56-xdebug
brew php56-xhprof
brew php56

## rcmdnk/file
tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew ack
brew android-sdk
brew ansible
brew autoconf
brew bash-completion
brew bison
brew boost
brew cmake
brew curl
brew editorconfig
brew freetype
brew gettext
brew gflags
brew ghostscript
brew git
brew git-flow
brew glog
brew gmp
brew icu4c
brew imagemagick
brew jbig2dec
brew jpeg
brew jq
brew legit
brew libpng
brew libtiff
brew libtool
brew libyaml
brew little-cms2
brew lz4
brew mecab
brew mecab-ipadic
brew nkf
brew openssl
brew p7zip
brew pandoc
brew pcre
brew pkg-config
brew q
brew readline
brew rmtrash
brew rocksdb
brew shellcheck
brew snappy
brew sqlite
brew subversion
brew the_silver_searcher
brew thrift
brew tig
brew tree
brew unixodbc
brew unrar
brew vim
brew wget
brew xz

# App Store applications
appstore Go2Shell
appstore Growl
appstore Janetter
appstore Keynote
appstore Simplenote
appstore Tweetbot
appstore Xcode

# Other commands
but not corresponding casks were found.
