[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]] 
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  " カラースキーマの適用はsource後じゃないと出来ないので遅延セット
  autocmd MyAutoCmd VimEnter * colorscheme molokai
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
